import { User, Team, Module, Submission, CreditTransaction, Notification } from '../types';

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'team-alpha',
    name: 'Team Alpha',
    teamLeadId: 'tl-1',
    memberIds: ['usr-1', 'usr-2'],
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'team-beta',
    name: 'Team Beta',
    teamLeadId: 'tl-2',
    memberIds: ['usr-3', 'usr-4'],
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'team-gamma',
    name: 'Team Gamma',
    teamLeadId: 'tl-1',
    memberIds: ['usr-5'],
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
];

export const INITIAL_USERS: User[] = [
  // Participants
  {
    uid: 'usr-1',
    name: 'Arun Kumar',
    email: 'arun@example.com',
    role: 'user',
    teamId: 'team-alpha',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    credits: 850,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'usr-2',
    name: 'Rahul Sharma',
    email: 'rahul@example.com',
    role: 'user',
    teamId: 'team-alpha',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    credits: 720,
    createdAt: new Date(Date.now() - 19 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'usr-3',
    name: 'Priya Patel',
    email: 'priya@example.com',
    role: 'user',
    teamId: 'team-beta',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
    credits: 680,
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'usr-4',
    name: 'Karthik Raja',
    email: 'karthik@example.com',
    role: 'user',
    teamId: 'team-beta',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    credits: 520,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'usr-5',
    name: 'Meena Reddy',
    email: 'meena@example.com',
    role: 'user',
    teamId: 'team-gamma',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=200',
    credits: 370,
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Team Leads
  {
    uid: 'tl-1',
    name: 'Vikram Singh (Team Lead Alpha & Gamma)',
    email: 'vikram.lead@example.com',
    role: 'team_lead',
    teamId: 'team-alpha',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    credits: 1240,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'tl-2',
    name: 'Ananya Verma (Team Lead Beta)',
    email: 'ananya.lead@example.com',
    role: 'team_lead',
    teamId: 'team-beta',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    credits: 980,
    createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Admin
  {
    uid: 'admin-1',
    name: 'Suresh Menon (Challenge Admin)',
    email: 'admin@tenworkspace.org',
    role: 'admin',
    avatar: '/s10-logo.png',
    credits: 0,
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_MODULES: Module[] = [
  {
    id: 'mod-1',
    title: 'Module 01 — Frontend Foundation',
    description: 'Build the base responsive interface for your assigned workspace using Tailwind CSS and React.',
    instructions: '1. Clone repository.\n2. Implement responsive dark mode layout.\n3. Verify component hierarchy and submit repository link.',
    creditValue: 100,
    deadline: '2026-08-20',
    status: 'active',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'mod-2',
    title: 'Module 02 — Database Integration',
    description: 'Connect Firestore database schema and manage persistent state for user resources.',
    instructions: '1. Set up Firestore collections.\n2. Write type-safe query adapters.\n3. Add atomic CRUD handlers and pass schema validation tests.',
    creditValue: 120,
    deadline: '2026-08-25',
    status: 'active',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'mod-3',
    title: 'Module 03 — Authentication & RBAC',
    description: 'Implement multi-role security flow for Users, Team Leads, and Admins.',
    instructions: '1. Set up Firebase Authentication.\n2. Create protected routes in React.\n3. Implement role authorization guards.',
    creditValue: 150,
    deadline: '2026-08-30',
    status: 'active',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'mod-4',
    title: 'Module 04 — Interactive Dashboard',
    description: 'Create metrics analytics, real-time status feeds, and team breakdown cards.',
    instructions: '1. Build responsive 12-column grid.\n2. Implement real-time listeners for submission state updates.\n3. Optimize mobile views.',
    creditValue: 180,
    deadline: '2026-09-05',
    status: 'active',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'mod-5',
    title: 'Module 05 — Final Integration & Polish',
    description: 'End-to-end testing, error handling, performance optimization, and live submission verification.',
    instructions: '1. Wire end-to-end verification and credit workflow.\n2. Run accessibility and performance checks.\n3. Deploy live production preview.',
    creditValue: 200,
    deadline: '2026-09-12',
    status: 'active',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

export const INITIAL_SUBMISSIONS: Submission[] = [
  {
    id: 'sub-101',
    moduleId: 'mod-1',
    userId: 'usr-1',
    teamId: 'team-alpha',
    githubUrl: 'https://github.com/arunkumar/ten-workspace-frontend',
    title: 'Frontend Foundation - Workspace Alpha Base',
    description: 'Implemented modular layout with Tailwind CSS and Inter/Poppins font hierarchy.',
    submittedAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    status: 'approved',
    reviewedBy: 'tl-1',
    reviewedAt: new Date(Date.now() - 11 * 86400000).toISOString(),
    approvedBy: 'admin-1',
    approvedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    userCreditsAwarded: 100,
    teamLeadCreditsAwarded: 100,
    reviewComment: 'Excellent UI responsiveness and strict design system adherence.',
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'sub-102',
    moduleId: 'mod-2',
    userId: 'usr-1',
    teamId: 'team-alpha',
    githubUrl: 'https://github.com/arunkumar/ten-workspace-firestore',
    title: 'Database Integration with Firestore Adapters',
    description: 'Clean schema integration with Firestore listeners for submissions.',
    submittedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    status: 'approved',
    reviewedBy: 'tl-1',
    reviewedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    approvedBy: 'admin-1',
    approvedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    userCreditsAwarded: 120,
    teamLeadCreditsAwarded: 120,
    reviewComment: 'Thorough Firestore error boundary implementation.',
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: 'sub-103',
    moduleId: 'mod-3',
    userId: 'usr-1',
    teamId: 'team-alpha',
    githubUrl: 'https://github.com/arunkumar/ten-workspace-auth',
    title: 'Auth & Protected Route Guards',
    description: 'Implemented RBAC rules and auth state persistence.',
    submittedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    status: 'verified',
    reviewedBy: 'tl-1',
    reviewedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    reviewComment: 'Verified. Code passes all security rule tests.',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'sub-104',
    moduleId: 'mod-1',
    userId: 'usr-2',
    teamId: 'team-alpha',
    githubUrl: 'https://github.com/rahul-sharma/frontend-foundation-v1',
    title: 'Frontend Foundation - Team Alpha Submission',
    description: 'Complete UI implementation for user and team lead viewports.',
    submittedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    status: 'approved',
    reviewedBy: 'tl-1',
    reviewedAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    approvedBy: 'admin-1',
    approvedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    userCreditsAwarded: 100,
    teamLeadCreditsAwarded: 100,
    reviewComment: 'Great layout implementation.',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'sub-105',
    moduleId: 'mod-2',
    userId: 'usr-2',
    teamId: 'team-alpha',
    githubUrl: 'https://github.com/rahul-sharma/database-module',
    title: 'Database Integration Module',
    description: 'Added transaction models for credit allocation.',
    submittedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    status: 'verified',
    reviewedBy: 'tl-1',
    reviewedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    reviewComment: 'Ready for admin approval.',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'sub-106',
    moduleId: 'mod-1',
    userId: 'usr-3',
    teamId: 'team-beta',
    githubUrl: 'https://github.com/priya-patel/workspace-m1',
    title: 'Module 01 - Frontend Foundation Beta',
    description: 'Clean responsive dark UI with custom badges.',
    submittedAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    status: 'approved',
    reviewedBy: 'tl-2',
    reviewedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    approvedBy: 'admin-1',
    approvedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    userCreditsAwarded: 100,
    teamLeadCreditsAwarded: 100,
    reviewComment: 'Verified component structure.',
    createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'sub-107',
    moduleId: 'mod-2',
    userId: 'usr-3',
    teamId: 'team-beta',
    githubUrl: 'https://github.com/priya-patel/workspace-m2',
    title: 'Module 02 - Database Integration Beta',
    description: 'Firestore persistence handlers for submissions.',
    submittedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    status: 'under_review',
    reviewedBy: 'tl-2',
    reviewedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    reviewComment: 'Under active inspection by Team Lead.',
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'sub-108',
    moduleId: 'mod-1',
    userId: 'usr-4',
    teamId: 'team-beta',
    githubUrl: 'https://github.com/karthik-raja/ten-workspace-mod1',
    title: 'Module 01 Frontend',
    description: 'Base UI components and theme tokens.',
    submittedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    status: 'submitted',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'sub-109',
    moduleId: 'mod-1',
    userId: 'usr-5',
    teamId: 'team-gamma',
    githubUrl: 'https://github.com/meena-reddy/workspace-gamma-1',
    title: 'Module 01 - Gamma Foundation',
    description: 'Tailwind CSS dark theme base UI.',
    submittedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    status: 'submitted',
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: 'sub-110',
    moduleId: 'mod-4',
    userId: 'usr-1',
    teamId: 'team-alpha',
    githubUrl: 'https://github.com/arunkumar/ten-workspace-dashboard',
    title: 'Module 04 - Dashboard Grid and Leaderboards',
    description: 'Implemented 12-column grid dashboard with Poppins typography.',
    submittedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    status: 'submitted',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

export const INITIAL_CREDIT_TRANSACTIONS: CreditTransaction[] = [
  {
    id: 'ctx-1',
    userId: 'usr-1',
    submissionId: 'sub-101',
    amount: 100,
    type: 'module_completion',
    description: 'Module 01 — Frontend Foundation approved (+100 credits)',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'ctx-2',
    userId: 'tl-1',
    submissionId: 'sub-101',
    amount: 100,
    type: 'team_lead_bonus',
    description: 'Team member Arun Kumar Module 01 approved (+100 credits)',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'ctx-3',
    userId: 'usr-1',
    submissionId: 'sub-102',
    amount: 120,
    type: 'module_completion',
    description: 'Module 02 — Database Integration approved (+120 credits)',
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: 'ctx-4',
    userId: 'tl-1',
    submissionId: 'sub-102',
    amount: 120,
    type: 'team_lead_bonus',
    description: 'Team member Arun Kumar Module 02 approved (+120 credits)',
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'usr-1',
    title: 'Submission Verified',
    message: 'Your Module 03 submission was verified by Team Lead Vikram Singh.',
    type: 'verification',
    read: false,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    link: '/submission/sub-103',
  },
  {
    id: 'notif-2',
    userId: 'usr-1',
    title: '+120 Credits Awarded',
    message: 'Admin approved Module 02. You received +120 credits!',
    type: 'credits',
    read: true,
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    link: '/profile',
  },
  {
    id: 'notif-3',
    userId: 'tl-1',
    title: 'New Submission Pending Review',
    message: 'Arun Kumar submitted Module 04 for review.',
    type: 'system',
    read: false,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    link: '/team-lead/dashboard',
  },
  {
    id: 'notif-4',
    userId: 'admin-1',
    title: 'Verified Submissions Awaiting Approval',
    message: '2 submissions are verified and ready for credit allocation.',
    type: 'approval',
    read: false,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    link: '/admin/dashboard',
  },
];
